### ISSUE TITLE
some different ?

### ISSUE THREAD

**Issue by luoww1992** [SHI-Labs/VMFormer#6] opened 2022-09-06 07:22 UTC
i notice you said in project-- residual connection and repeated blocks are omitted for simplicity.
so:
Q1:  the missing part is in train code or in inference code ?
    Q1.1: if in train code, when i try to train a new model myself, what effect does it have ？loss will get bigger ？result will 
go bad ? and some others ?
    Q1.2: if in inference code, when i try to train a new model myself, what effect does it have ？like Q1.1.

Q2:  I'm getting ready to train a new model myself ? 
    Q2.1: can you give me some advices, are there  some things to be careful ?
    Q2.2: can you share a checkpoint ？

**Comment by chrisjuniorli** [comment] 2022-09-06 15:52
Thanks for your interest in our work. Here are the response to your questions:

Q1: The missing part was referring to the figure in the paper, not in the codes. Both residual connection and repeated blocks are explicitly coded in training and inference code.

Q1.1: When you train the new model, if you want to reproduce our results, please follow the [Getting_Started](https://github.com/SHI-Labs/VMFormer/blob/main/GETTING_STARTED.md). If you want to train on your own datasets, the model will get bigger if you use more encoder or decoder blocks.

Q1.2: During inference, it should be fine if you use the same configuration (number of encoders, number of decoders, etc. ) to the new model you trained.

Q2: If you want to train the model yourself, I suggest following the [Getting_Started](https://github.com/SHI-Labs/VMFormer/blob/main/GETTING_STARTED.md) and we have a [checkpoint](https://drive.google.com/file/d/1q2Rm-Rp42bQA4zIbCqPzJ9GG6P7SQGmq/view) in the model zoo. I'll happy to answer follow-up questions when you encounter any problems.

**Comment by chrisjuniorli** [comment] 2022-09-21 18:08
I'll close this issue since no further updates. Feel free to reopen it if you have further questions.

**Closed as completed by chrisjuniorli** 2022-09-21 18:08 UTC
